checkpoint_path: ${work_dir}/logs/vae_mnist/2021-10-18-14-15/checkpoints/sample-epoch=99.ckpt

# Langevin diffusion configuration
step_size_init: 0.02
num_chain: 10
total_step: 5
validation_total_step: 1000

learning_rate_init: 3e-4