_target_: src.almond.ALMOND

checkpoint_path: ${work_dir}/logs/vae_process/2021-10-20-14-20/checkpoints/sample-epoch=417.ckpt

# Langevin diffusion configuration
step_size_init: 0.02
total_step: 30
num_chain: 10

min_lr: 0.00001
max_lr: 0.0003

validation_total_step: 1000
num_latent_variable_samples: 300
