_target_: src.almond.ALMOND

checkpoint_path: ${work_dir}/logs/vae_zhai/2021-10-17-23-34/checkpoints/sample-epoch=96.ckpt

# Langevin diffusion configuration
step_size_init: 0.02
num_chain: 10
total_step: 30
validation_total_step: 1000
num_latent_variable_samples: 300


min_lr: 0.0001
max_lr: 0.0003