_target_: src.almond.ALMOND

checkpoint_path: ${work_dir}/logs/vae_mnist/2021-10-31-16-21/checkpoints/sample-epoch=493.ckpt

# Langevin diffusion configuration
step_size_init: 0.02
total_step: 1
num_chain: 1
image: True

min_lr: 0.0001
max_lr: 0.0003

validation_total_step: 310
num_latent_variable_samples: 300