_target_: src.vae.VAE

output_dim: 784
latent_dim: 20

learning_rate: 0.0003

# Config Encoder
encoder_architecture: MLP
encoder_hidden_dim: [500, 500] # from input -> latent dim

# Config Decoder
decoder_architecture: MLP
decoder_hidden_dim: [500, 500] # from latent -> input dim
decoder_positive_constraint: False