_target_: data.datamodules.singlecell.PROCESS_DataModule

data_dir: ${work_dir}/data/SINGLECELL/process_train.pkl

batch_size: 128
train_val_test_split: [0.85, 0.05, 0.1]
num_workers: 16
pin_memory: False

num_train_data: 1000
num_val_data: 100
